### ISSUE TITLE
Provide an API to allow validation of "embedded" schema

### ISSUE THREAD

**Issue by dmak** [bjansen/swagger-schema-validator#25]
Let's consider this example of URL parameter declaration:
```
parameters:
  - name: userId
    in: path
    required: true
    example: "akb5719"
    schema:
      type: string
```
Here the schema definition comes with the example. As far as I can see current API does not allow to validate such case.

To achieve this `SwaggerValidator` should probably allow validation without schema location:

```
SwaggerValidator.forJsonNode(parameter.get("schema"), Collections.emptyMap()).validate(parameter.get("example"));
```
